import * as fs from "node:fs/promises";
import * as path from "node:path";

const CLIENT_SRC = path.join("src", "danger-pi", "extensions", "viewer", "viewer-client.ts");
const GENERATED_FILE = path.join("src", "danger-pi", "extensions", "viewer", "viewer-client.generated.ts");
const HTML_SHELL_SRC = path.join("src", "danger-pi", "extensions", "viewer", "viewer-shell.html");
const HTML_GENERATED_FILE = path.join("src", "danger-pi", "extensions", "viewer", "viewer-shell.generated.ts");

async function main() {
	const result = await Bun.build({
		entrypoints: [CLIENT_SRC],
		minify: true,
		target: "browser",
	});

	if (!result.success) {
		console.error("Build failed");
		for (const message of result.logs) {
			console.error(message);
		}
		process.exit(1);
	}

	const bundle = await result.outputs[0].text();
	const content = `// Auto-generated by scripts/generate-viewer-bundle.ts - DO NOT EDIT

export const VIEWER_CLIENT_JS = ${JSON.stringify(bundle)};
`;

	await fs.writeFile(GENERATED_FILE, content);
	console.log(`Generated ${GENERATED_FILE}`);

	const html = await fs.readFile(HTML_SHELL_SRC, "utf-8");
	const htmlContent = `// Auto-generated by scripts/generate-viewer-bundle.ts - DO NOT EDIT

export const VIEWER_SHELL_HTML = ${JSON.stringify(html)};
`;
	await fs.writeFile(HTML_GENERATED_FILE, htmlContent);
	console.log(`Generated ${HTML_GENERATED_FILE}`);
}

main().catch(console.error);
