default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "lint-staged"
name = "lint-staged"
entry = "bunx lint-staged"
language = "system"
pass_filenames = false
stages = ["pre-commit"]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"

[[repos.hooks]]
id = "conventional-pre-commit"
stages = ["commit-msg"]
